export const GET_DATA_REQUEST="GET_DATA_REQUEST";
export const GET_DATA_SUCCESS="GET_DATA_SUCCESS";
export const GET_DATA_FAILURE="GET_DATA_FAILURE";
export const SET_DATA_REQUEST="SET_DATA_REQUEST";
export const SET_DATA_SUCCESS="SET_DATA_SUCCESS";
export const SET_DATA_FAILURE="SET_DATA_FAILURE";