export const GET_ADDTOCART_REQUEST="GET_ADDTOCART_REQEST"
export const GET_ADDTOCART_SUCCESS="GET_ADDTOCART_SUCCESS";
export const GET_ADDTOCART_FAIL="GET_ADDTOCART_FAIL"
export const DELETE_ADDTOCART_SUCCESS="DELETE_ADDTOCART_SUCCESS";
export const DELETE_ADDTOCART_FAIL="DELETE_ADDTOCART_FAIL"